version: '2'
services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    links:
      - "hopsoft"
  hopsoft:
    image: hopsoft/graphite-statsd
    ports:
     - "8080:80"
     - "2003-2004:2003-2004"
     - "2023-2024:2023-2024"
     - "8125:8125/udp"
     - "8126:8126"
  example:
    image: alpine
    links:
          - "hopsoft"
    volumes:
     - "./generator.sh:/generator.sh"
    command: /bin/sh /generator.sh


